### ISSUE TITLE
Hot to edit HID descriptor

### ISSUE THREAD

**Issue by ghost** [manthi4/AndroidPIeBluetoothMouse#2]
...

**Comment by manthi4** [comment]
Hello Ganime!, 

That's a great question. I found this resource: https://eleccelerator.com/tutorial-about-usb-hid-report-descriptors/#:~:text=Devices%20define%20their%20data%20packets,and%20bit%20in%20the%20packet.
 to be super useful for crafting the hid descriptor. The variable labeled "descriptor" at the top of MleMouse.java is what you will have to modify. The bits in that variable are sent to the computer upon initiali connection to tell it what kind of bluetooth device it is talking to and establish some communication conventions. You might to parse the document “Device Class Definition for HID” mentioned in the above link to figure out what the descriptor codes for other devices are.

Also fyi, this repo is still under development. There are currently issues with reconnecting to bluetooth devices. But I plan on eventually fixing those and publishing this as an android library.
